### ISSUE TITLE
徳が多すぎるとエラーが出る

### ISSUE THREAD

**Issue by tamaroh** [azarashi-bird/azarashi-bird#33]
afterViewの配列の個数よりも多い徳を積むとエラーが出る
来世の姿のロジックを決め切ることで解決可能？

**Comment by Kiki-her** [comment]
Next MVPまではとりあえず来世分岐せず、単純に徳数で変化する？n*2でafterlifeのインデックス番号n-1に進化はどうでしょうか。1徳だと弱々しいWiFi、4徳だと猛威を振るう杉花粉、9徳だと醤油のタレビン、のような形で。

**Comment by skakeru0920** [comment]
indexを `Math.floor((userTokus.length % 45) / 3)` って感じで表示してとりあえず回避してます（頭打ちになったら初めからにループ。仮実装として、徳3つにつき来世の姿が変わるようにしています。）
