### ISSUE TITLE
useEffect内でも2回DBにアクセスしてしまう？

### ISSUE THREAD

**Issue by tamaroh** [azarashi-bird/azarashi-bird#42]
console.logでふたつログが吐かれるのが気になっています。Calender.tsxで確認済み。他のファイルでもそうかな…？解決策分かってたらシェアしてください！

**Comment by skakeru0920** [comment]
reactの開発環境でのみuseEffectが2回呼ばれる的なのみたことある気がする。。。
今回の件に関してマッチしてるのかわからないけど念の為共有しま！

**Comment by skakeru0920** [comment]
https://www.ey-office.com/blog_archive/2021/06/30/i-found-out-why-the-component-is-drawn-twice-in-the-react/

**Comment by skakeru0920** [comment]
現状大丈夫そう！
useEffectフックの設定が悪かった？
