### ISSUE TITLE
みんなの徳　表示が1ヶ月ずれている

### ISSUE THREAD

**Issue by tamaroh** [azarashi-bird/azarashi-bird#43]
ひと月前の日付で表示されているもよう（9/26投稿→表示は8/26）

**Comment by skakeru0920** [comment]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

>返値 地方時に基づき、与えた日付の「月」を表す 0 から 11 までの間の整数値。0 は 1 月、1 は 2 月、11 は 12 月に対応します。

getMonth() の使い方ミスって表示月がずれてたの直しました！
